### ISSUE TITLE
Return the token after verifying on singpass app

### ISSUE THREAD

**Issue by varunbhalerao56** [singpass/Singpass-app-webview-client#3]
(myInfo API) Hey, we are using flutter for our application and currently, we are trying to implement the android version of it. The stg env works great and all but in the production version of the application we are unable to receive back the token after the user presses log in. It would be great if anybody could help regarding this as it is very essential for us to make this work.

**Comment by kenneth-leong-gt** [comment]
Hi, please contact support@myinfo.gov.sg for any queries on MyInfo integration.
