### ISSUE TITLE
SDK Limitation, only QR links are handled

### ISSUE THREAD

**Issue by ExpensiveBelly** [singpass/Singpass-app-webview-client#5]
Hello,

If we were to click on the purple area in the screenshot below, the link is the following: `intent://app.singpass.gov.sg#Intent;scheme=https;package=sg.ndi.sp;S.browser_fallback_url=https://app.singpass.gov.sg;end` and that is not handled by the SDK, we as developers need to handle that link independently, which I find quite limiting, because I expected this SDK to handle all the `intent` links related to Singpass.

<img src="https://user-images.githubusercontent.com/6824465/168616317-fa4a69a2-222f-4120-baca-bf1f657ae2fc.png" width="360" height="760">

**Comment by kenneth-leong-gt** [comment]
Can you provide the mockpass URL?

**Comment by ExpensiveBelly** [comment]
https://test.api.myinfo.gov.sg/mockpass-sp/authorize?scope=openid&response_type=code&redirect_uri=https%3A%2F%2Ftest.api.myinfo.gov.sg%2Fserviceauth%2Fmyinfo-com%2Fv1%2Fauthenticate&client_id=NDI-AUTHCOM&state=xWGu***&nonce=6PUa***

**Comment by kenneth-leong-gt** [comment]
It should be handled, do you have a snippet of your webviewclient impementation?

**Comment by ExpensiveBelly** [comment]
It's not handled, 

```

**Comment by ExpensiveBelly** [comment]
If you try this `intent://app.singpass.gov.sg#Intent;scheme=https;package=sg.ndi.sp;S.browser_fallback_url=https://app.singpass.gov.sg;end`

this function will return `false`
```
override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
        val uri = request.url
        return UrlHandler.handleableBySingpassApp(uri, view)
    }
```

it goes inside here:
```
fun handleableBySingpassApp(uri: Uri, view: WebView): Boolean {

        val isSingpassQrCode = isSingpassQrCode(uri)

        if (!isSingpassQrCode)
            return false // <-- It returns here

        handleSingpassQrCode(uri, view.context, view)

//            Return true if this function handled the URL
        return true
    }
```

`val isSingpassQrCode` equals `false` at that point and it returns.


My implementation simply extends yours and call super:
```
public class WebViewClientInterceptor extends SingpassWebViewClient {

@Override
    public boolean shouldOverrideUrlLoading(@NonNull WebView view, @NonNull WebResourceRequest request) {
        boolean shouldOverrideUrlLoading = super.shouldOverrideUrlLoading(view, request);
        if (!shouldOverrideUrlLoading)
            return URLUtils.isUrlHandled(request.getUrl().toString(), view); 
        else return true;
    }
}
```

**Comment by kenneth-leong-gt** [comment]
`isSingpassQrCode()` returns false as this intent url `intent://app.singpass.gov.sg#Intent;scheme=https;package=sg.ndi.sp;S.browser_fallback_url=https://app.singpass.gov.sg;end` is not a valid Singpass login url. it is missing the proper path and query params for a Singpass login QR. Thanks for reporting. I will contact the relevant developers to get the mockpass page fixed.

**Comment by kenneth-leong-gt** [comment]
Upon checking with the devs of mockpass, the text portion should not be clicked, and on the actual Singpass QR page, there will not be such a a clickable element. The handling by the library is correct. Just to close the loop.
